version: 2

updates:
  # GHA
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    assignees:
      - "TheophileDiot"
    reviewers:
      - "TheophileDiot"
    commit-message:
      prefix: "deps/gha"
    target-branch: "dev"

  # Docker
  - package-ecosystem: "docker"
    directory: "/tests/misc/api"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    assignees:
      - "TheophileDiot"
    reviewers:
      - "TheophileDiot"
    commit-message:
      prefix: "deps/api"
    target-branch: "dev"

  - package-ecosystem: "docker"
    directory: "/tests/linux"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    assignees:
      - "TheophileDiot"
    reviewers:
      - "TheophileDiot"
    commit-message:
      prefix: "deps/linux"
    target-branch: "dev"

  # Python
  - package-ecosystem: "pip"
    directory: "/misc"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    assignees:
      - "TheophileDiot"
    reviewers:
      - "TheophileDiot"
    commit-message:
      prefix: "deps/misc"
    target-branch: "dev"
  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    assignees:
      - "TheophileDiot"
    reviewers:
      - "TheophileDiot"
    commit-message:
      prefix: "deps/tests"
    target-branch: "dev"

  # Terraform
  - package-ecosystem: "terraform"
    directory: "/tests/terraform"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    assignees:
      - "fl0ppy-d1sk"
    reviewers:
      - "fl0ppy-d1sk"
    commit-message:
      prefix: "deps/terraform"
    target-branch: "dev"
